---
title: "Shanki Chamindhya"
show_downloads: false
theme: jekyll-theme-leap-day

description: |
  <style>
    .profile-container {
      display: flex;
      align-items: center;
      justify-content: flex-start;
      text-align: left;
      padding: 20px;
      max-width: 900px;
      margin: 0 auto;
      background-color: #f8f9fa;
      border-radius: 10px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .profile-image {
      display: flex;
      justify-content: center;
      margin-right: 20px;
    }

    .profile-image img {
      width: 180px;
      height: 180px;
      border-radius: 50%;
      object-fit: cover;
      border: 3px solid #007acc;
    }

    .profile-details {
      flex-grow: 1;
      padding: 10px;
      font-family: Arial, sans-serif;
      color: #333;
    }

    .contact-info {
      display: flex;
      flex-direction: column;
      gap: 10px;
      margin-top: 20px;
    }

    .contact-item {
      display: flex;
      align-items: center;
      gap: 10px;
    }

    .contact-item img {
      width: 20px;
      height: 20px;
    }

    @media (max-width: 600px) {
      .profile-container {
        flex-direction: column;
        align-items: center;
        text-align: center;
      }
      .profile-image {
        margin-bottom: 20px;
      }
    }
  </style>

  <div class="profile-container">
    <div class="profile-image">
      <img src="assessment/shanki.me.jpg" alt="Shanki Chamindhya">
    </div>

    <div class="profile-details">
      <h2>Contact</h2>
      <div class="contact-info">
        <div class="contact-item">
          <img src="assessment/location.png" alt="Location Icon">
          <span>Kurunegala, Sri Lanka</span>
        </div>
        <div class="contact-item">
          <img src="assessment/phone-circle.png" alt="Phone Icon">
          <span>+94 712327929</span>
        </div>
        <div class="contact-item">
          <img src="assessment/mailicon.png" alt="Email Icon">
          <a href="mailto:chamindhyashanki@gmail.com">chamindhyashanki@gmail.com</a>
        </div>
        <div class="contact-item">
          <img src="assessment/GitHubicon.png" alt="GitHub Icon">
          <a href="https://github.com/Shanki-chaminda" target="_blank">github.com/Shanki-chaminda</a>
        </div>
        <div class="contact-item">
          <img src="assessment/linkdinicon.png" alt="LinkedIn Icon">
          <a href="http://linkedin.com/in/shanki-chamindhya-578909255" target="_blank">linkedin.com/in/shanki-chamindhya</a>
        </div>
      </div>
    </div>
  </div>
